### ISSUE TITLE
VWF Patch- Script bug while trading Scent Seeds 

### ISSUE THREAD

**Issue by Cralex** [Drenn1/ages-disasm#10]
While playing the VWF Edition 1.0 from romhacking.net, I encountered a bug with the script while trying to trade 10 Scent Seeds for the Power Bracelet in the Tokay trading post. The Tokay explained what the “hoop” was twice in a row, and then offered to trade it for the Shovel, even if you already have the Scent Seeds he’s asking for. However, accepting the trade will actually give you the Power Bracelet in exchange for the Scent Seeds, like it should.

https://www.dropbox.com/s/50j1v88cyb5siuj/scentseedtrade.MOV?dl=1

Full disclosure: I’m playing a copy that’s been injected into 3DS virtual console, that is also patched with the Forced GBA Advanced Mode and GBC Palettes patches. I made a backup of my saved game with the intention to test it without other patches, but I won’t be able to get it on my computer for a few days.

**Comment by Stewmath** [comment]
Thanks for the report. I'm pretty sure I played through the game with this patch, but maybe I mashed through that too quickly.

**Comment by Stewmath** [comment]
This has technically been long since fixed so I'll close the issue. The VWF hack itself has not been updated, though, and I don't know if/when I'll get to that.

I will also note that the same bug used to manifest itself in Seasons also. I believe it occurred when you selected the "know-it-all birds" tile on the map; it would display the wrong text. Of course, there was no VWF hack for that game, but it used to affect ROMs built with the disassembly in general. Should be fine now though.
