### ISSUE TITLE
Wave scrolling

### ISSUE THREAD

**Issue by fortwoone** [Drenn1/ages-disasm#17]
Hello again,
I wanted to know:
`
@sineWave:
	.db $00 $0d $19 $26 $32 $3e $4a $56
	.db $62 $6d $79 $84 $8e $98 $a2 $ac
	.db $b5 $be $c6 $ce $d5 $dc $e2 $e7
	.db $ed $f1 $f5 $f8 $fb $fd $ff $ff`
What is this supposed to be?

**Comment by fortwoone** [comment]
Also, how are the sine waves's amplitudes calculated?

**Comment by Stewmath** [comment]
Not sure if you got your answer already, but: those ".db" values are just predefined values in a sine wave. If you were to graph these values you would see that it forms a sine wave - starting at 00 and going up to ff. I guess it is only the first quarter of a full cycle (doesn't go back down).

As shown in the comment, it is almost possible to replace those predefined values with a built-in directive in WLA:
```
; This almost works to replace the above, just a few values are off-by-1 for some reason.
;	.dbsin 0, 31, 90/32, $100, 0
```

But since the values weren't an exact match I couldn't use that. I forget exactly what the semantics of that directive are, but basically it would define a series of bytes in a sine wave with a given amplitude.

Generally the discord server is a better place to ask questions like this. Even though I am only online once a week lately, either I should see any questions eventually or someone else will respond.
